### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sanceilaks** [zertmark/cryptor_remake#1]
`
                  ▄▄  ▄▄▄▄▄▄▄▄                                ▄▄        ▄▄
       ██        ██   ▀▀▀▀▀███                        ██       █▄        █▄
      ██        ██        ██▀    ▄████▄    ██▄████  ███████     █▄        █▄
     ██        ██       ▄██▀    ██▄▄▄▄██   ██▀        ██         █▄        █▄
    ▄█▀       ▄█▀      ▄██      ██▀▀▀▀▀▀   ██         ██          █▄        █
   ▄█▀       ▄█▀      ███▄▄▄▄▄  ▀██▄▄▄▄█   ██         ██▄▄▄        █▄        █▄
  ▄█▀       ▄█▀       ▀▀▀▀▀▀▀▀    ▀▀▀▀▀    ▀▀          ▀▀▀▀         █▄        █▄

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/aes-0.5.0/lib/aes/aes.rb:151: warning: constant OpenSSL::Cipher::Cipher is deprecated

Generated random initialization vector: TtonPJnYxmRL4s33lUdTNA==
Starting...
Parsing...Dir
Encrypting: test.txtTraceback (most recent call last):
        10: from ./encryptor.rb:75:in `<main>'
         9: from ./encryptor.rb:41:in `main'
         8: from ./encryptor.rb:52:in `search'
         7: from ./encryptor.rb:52:in `each'
         6: from ./encryptor.rb:56:in `block in search'
         5: from ./encryptor.rb:66:in `encrypt'
         4: from ./encryptor.rb:66:in `each'
         3: from ./encryptor.rb:67:in `block in encrypt'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/aes-0.5.0/lib/aes/aes.rb:5:in `encrypt'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/aes-0.5.0/lib/aes/aes.rb:54:in `encrypt'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/aes-0.5.0/lib/aes/aes.rb:155:in `_setup': undefined method `unpack' for nil:NilClass (NoMethodError)`

**Comment by zertmark** [comment]
Это версия для Linux. Ты точно скачал гемы: slop,aes?

**Comment by Sanceilaks** [comment]
Да

**Comment by zertmark** [comment]
Пришли мне аргументы запуска
